################################### Default Configuration ############################
baseurl = ""
title = "Vex | hugo landing page template"
theme = "vex-hugo-main"
publishDir = "server"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here

########################### Default parameters ##########################
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    # theme = "vex-hugo-main"
    title = "Vex Hugo"
    [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [[languages.en.menu.main]]
    name = "Products"
    url = "products"
    weight = 2
    [[languages.en.menu.main]]
    name = "Blog"
    url = "blog"
    weight = 3
    [[languages.en.menu.main]]
    name = "Review"
    url = "/#testimonial"
    weight = 4
    [[languages.en.menu.main]]
    name = "Contact"
    url = "contact"
    weight = 5
    [[languages.en.menu.footer]]
    name = "Blog"
    url = "blog"
    weight = 1
    [[languages.en.menu.footer]]
    name = "Contact"
    url = "contact"
    weight = 2
    [[languages.en.menu.footer]]
    name = "Terms & Conditions"
    url = "terms-conditions"
    weight = 3
    [[languages.en.menu.footer]]
    name = "Privacy Policy"
    url = "privacy-policy"
    weight = 4

  [languages.ko]
    languageName = "한국어"
    contentDir = "content/korean"
    weight = 2
    title = "Vex Hugo (Korean)"
    [languages.ko.params]
      currency = "₩"
    [[languages.ko.menu.main]]
    name = "홈"
    url = "/"
    weight = 1
    [[languages.ko.menu.main]]
    name = "제품"
    url = "products"
    weight = 2
    [[languages.ko.menu.main]]
    name = "블로그"
    url = "blog"
    weight = 3
    [[languages.ko.menu.main]]
    name = "리뷰"
    url = "/#testimonial"
    weight = 4
    [[languages.ko.menu.main]]
    name = "연락처"
    url = "contact"
    weight = 5
    [[languages.ko.menu.footer]]
    name = "블로그"
    url = "blog"
    weight = 1
    [[languages.ko.menu.footer]]
    name = "연락처"
    url = "contact"
    weight = 2
    [[languages.ko.menu.footer]]
    name = "이용 약관"
    url = "terms-conditions"
    weight = 3
    [[languages.ko.menu.footer]]
    name = "개인정보 처리방침"
    url = "privacy-policy"
    weight = 4

[params]
logo = "images/logo.png"
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# currency
currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io


# unsafe html
[markup.goldmark.renderer]
unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
# JS Plugins



# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

# Portone V2 
[params.portone]
  store_id = "store-9f6b78d6-2b0d-4a7c-96c4-7e4adb83bed9"
  inicis_channel_key = "channel-key-54930405-2c88-4283-9be0-298b3d1c117a"
  kakaopay_channel_key = "channel-key-3f5d70b2-ea6a-4261-a72b-23745a45524b"
  korean_payment_channel_key = "channel-key-9cdf78c0-a02b-46fc-bff4-57dd47c3ad7b"

# PocketBase
[params.pocketbase]
  url = "http://127.0.0.1:8090"
  
  [params.pocketbase.oauth]
    [params.pocketbase.oauth.google]
      enable = true
    [params.pocketbase.oauth.kakao]
      enable = true
    [params.pocketbase.oauth.naver]
      enable = false



# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours
