
###################################### Navigation Korean ######################################

[[main]]
name = "홈"
url = "/"
weight = 1

[[main]]
name = "제품"
url = "products"
weight = 2

[[main]]
name = "블로그"
url = "blog"
weight = 3

[[main]]
name = "리뷰"
url = "/#testimonial"
weight = 4

[[main]]
name = "연락처"
url = "contact"
weight = 5

# footer menu
[[footer]]
name = "블로그"
url = "blog"
weight = 1

[[footer]]
name = "연락처"
url = "contact"
weight = 2

[[footer]]
name = "이용 약관"
url = "terms-conditions"
weight = 3

[[footer]]
name = "개인정보 처리방침"
url = "privacy-policy"
weight = 4
