########################### Default parameters ##########################
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    # theme = "vex-hugo-main"
    title = "Vex Hugo"

  [languages.ko]
    languageName = "한국어"
    contentDir = "content/korean"
    weight = 2
    title = "Vex Hugo (Korean)"
    [languages.ko.params]
      currency = "₩"

[params]
logo = "images/logo.png"
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# currency
currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io


# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"



# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Portone V2
[params.portone]
  store_id = "store-4ff4af41-85e3-4559-8eb8-0d08a2c6ceec"
  inicis_channel_key = "channel-key-54930405-2c88-4283-9be0-298b3d1c117a"
  kakaopay_channel_key = "channel-key-3f5d70b2-ea6a-4261-a72b-23745a45524b"
  korean_payment_channel_key = "channel-key-9cdf78c0-a02b-46fc-bff4-57dd47c3ad7b"

# PocketBase
[params.pocketbase]
  url = "http://127.0.0.1:8090"



# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours






